### ISSUE TITLE
When I type "learn" in the command line, it says the test directory is empty

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/js-functions-lab#14]
For the js-functions lab, when I am in my local directory and type "learn" into the command line, it says, "This directory doesn't appear to have any specs in it." I can run the tests by doing npm test and see that they are all passing, but I can't get the "Run local tests" button to turn green on my learn page to move on to the next lesson.

**Comment by JessRudder** [comment]
@ldgarber use `pwd` command in terminal to see which directory you are in.  If it is not the directory for the lab you're currently working on you will need to use `cd` to get to the directory for the lab you're working on.  If you're still having this issue, please use the "Ask a Question" feature in Learn to get help from a Learn Expert.
