### ISSUE TITLE
Suggestion - Funcitons lab

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-functions-lab#20]
Spent an unnecessary amount of time here because I didn't know that you needed to use backticks ( ` ), and not single or double quotes to exclude variables from being literals in the string.

Maybe a one or 2 sentence call out about backticks would save other some time as well? - food for thought.

**Comment by gj** [comment]
Hey @ahg1992 !

How to interpolate is covered in the Strings Lab, four lessons before this one. That being said, I removed the double-quotes from the instructions for this lab to avoid any unnecessary confusion (14b25cea649bd9ff0accfe5bc4b330247aa39af6).

Thanks for pointing it out!
