### ISSUE TITLE
failed 

### ISSUE THREAD

**Issue by meirj3439** [learn-co-curriculum/js-functions-lab#25]
this is not specific to this lab bur by every lab if you fail it says falled in stead of failed by the side where its tells your your progress and if you've forked the lab or not

**Comment by gj** [comment]
Hi @meirj3439 — it definitely says `failed`. I think this might be an issue with the resolution of your monitor. 🙂

**Comment by meirj3439** [comment]
Ok np

**Comment by meirj3439** [comment]
![capture](https://user-images.githubusercontent.com/30475924/29082597-faa04522-7c33-11e7-84a6-27db024a8c1c.PNG)
look at this

**Comment by meirj3439** [comment]
@gj

**Comment by gj** [comment]
Here it is at higher resolution:

![](https://user-images.githubusercontent.com/17556281/29085098-284aab72-7c3c-11e7-99b6-d2c9a32168dd.png)

**Comment by gj** [comment]
@meirj3439 mind providing your screen resolution? Would love to test the site on similar settings to make sure everything looks good at all resolutions. 🙂

**Comment by meirj3439** [comment]
1920×1080
23.8 inch screen

**Comment by gj** [comment]
Thanks @meirj3439 ! Passed along to our product team. 🙂

**Comment by meirj3439** [comment]
Thanks
