### ISSUE TITLE
How to make functions

### ISSUE THREAD

**Issue by nxtezzz** [learn-co-curriculum/js-functions-lab#28]
hey im making functions in learn IDE and here's the problem. I can create a function like : 

function happyHolidays
console.log("Happy Holidays!!")
i am positive i am doing everything correct and have even copy pasted some of the provided codes and they all give me the same error. 

When i type into the console or where i enter the code: _function HappyHolidays_  i always get this weird thing in the console where instead of a reply i just get this weird arrow that pops up, like a directory or something its strange, http://prntscr.com/gwqpsm

and i never can even get a response to any of my functions :(

**Comment by maxwellbenton** [comment]
Hi @nxtezzz,

Sorry to hear that you had difficulty with this lab. Looking at the provided example, it looks like you are missing syntax, specifically the curly braces and parentheses. The function example you provided should be written like the following:

```
function happyHolidays() {
  console.log("Happy Holidays!!")
}
``` 

This syntax is required in order for JavaScript to recognize this as a function definition.
