### ISSUE TITLE
Task 4 Test - Potential Confusion For Students

### ISSUE THREAD

**Issue by david-dest01** [learn-co-curriculum/js-functions-lab#29]
**Test**
  describe('holidayCountdown(holiday, days)', () => {
    it('returns "It\'s ${days} days until ${holiday}!"', () => {
      expect(holidayCountdown("Mother's Day", 20)).toEqual("It's 20 days until Mother's Day!")

**JS User Input**
function holidayCountdown(holiday, days) {
  return(`It\'s ${days} days until ${holiday}!`)

Comment
(holiday, days) parameters being flipped is a bit unintuitive when comparing with the return sentence. May want to consider flipping the two parameters to mitigate student confusion. That's assuming this was not intentional!

**Comment by maxwellbenton** [comment]
Hi @david-dest01,

Thank you for this feedback. We've updated the instructions for this lab and now specifically point out that the `holiday` parameter is expected to be passed in first, followed by `days`, even though the returned string uses `days` first, which should help prevent this confusion for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
