### ISSUE TITLE
Backtick Information Missing

### ISSUE THREAD

**Issue by PlatypusBiscuit** [learn-co-curriculum/js-functions-lab#30]
I would like to bring attention to the lack of information in the Functions Lab about the necessity of backticks when using template literals like `${name}`. It took me a good 20 minutes of trial & error and googling before I discovered the whole issue was that I was using normal apostrophes ( ' ) instead of backticks ( ` ). I don't think there was any mention of this, but if it was mentioned, I missed it, and perhaps it should be repeated! I'm just trying to help out my fellow students and I hope this can improve the lessons!

**Comment by maxwellbenton** [comment]
Hi @PlatypusBiscuit,

Thank you for providing this feedback. We've updated this lesson's instructions to go into further detail on template literals and the required syntax, including additional examples to show the difference between them and regular concatenation with operators. This should help avoid confusion for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about this!
