### ISSUE TITLE
unable to respond to my question in chat windows for question.

### ISSUE THREAD

**Issue by tommy78savage** [learn-co-curriculum/js-functions-lab#31]
unable to respond to my question in chat windows for question. submit button on chat and submit button in snippet do not work in learn lab.

**Comment by maxwellbenton** [comment]
Hi @tommy78savage,

I'm sorry to hear you were having difficulty with our chat feature. I hope you were able to get assistance. If you happen to still be using the Learn platform and encounter this sort of thing again, please reach out to support@learn.co for additional assistance.
