### ISSUE TITLE
Question 4 Parameter word order.

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-functions-lab#34]
The question asks for a return string of return `It\'s ${days} days until ${holiday}!` 

To pass the test the parameter needs to have (days,holiday) in it but has to be backwards to the string meaning it has to be (holiday,days).  In a real life code the order wouldn't matter but for the test it does.  
Very confusing for new students learning functions and it's parameters.

**Comment by occipudding** [comment]
6/6/18, encountered this same issue as well.

**Comment by MGortz** [comment]
15/1/2019, as above

**Comment by kpneylon** [comment]
so how did you all get past it?

**Comment by maxwellbenton** [comment]
Hi @ghost,

Thank you for providing this feedback. We've updated this lesson's instructions to include additional guidance on question four. The readme now points out that the tests will expect the `holiday` parameter first, followed by `days`, even though `days` is used first in the returned string.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience!
