### ISSUE TITLE
README says there are no tests and there are tests

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/js-functions-lab#4]
Looks like this lab was just updated and added tests. The first paragraph of the README says there aren't any tests. Causes confusion for students.

@pletcher

**Comment by aturkewi** [comment]
To add to this, running `learn` does not bring up the tests. Instead student gets "This directory doesn't appear to have any specs in it." This is currently marked as a lab and students cannot pass it.

**Comment by pletcher** [comment]
They might have to update their learn gem -- if that doesn't fix it, lemme know!
