### ISSUE TITLE
Functions Lab

### ISSUE THREAD

**Issue by dmoniques** [learn-co-curriculum/js-functions-lab#43]
Hello. I'm failing Functions Lab. My error message says that I've not defined the function names in index-test.js. Can't figure out what I'm doing wrong. The questions seem so cut and dry.

**Comment by maxwellbenton** [comment]
Hi @dmoniques,

Sorry to hear you were having trouble with this lesson. We've updated the instructions to provide better guidance, including additional examples of the required syntax for template literals. If you are still using the Learn platform, we recommend reaching out to the Ask A Question team if you get stuck again. We have technical coaches online that will be able to assist you more rapidly.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
