### ISSUE TITLE
question 3 answer stating happyHolidaysTo is define

### ISSUE THREAD

**Issue by LuisCintron** [learn-co-curriculum/js-functions-lab#46]
been breaking my head with this question but i see a lot of people are having the same issues. please revise, thanks

**Comment by maxwellbenton** [comment]
Hi @devfromthebronx,
 
Sorry to hear you were having difficulty with this lab. We've updated the instructions to provide better guidance, specifically around template literals. The updated instructions go into additional examples of the required syntax for template literals to help ensure future students will not face the same problem that you encountered.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
