### ISSUE TITLE
Has 3 lights instead of 2 -- no tests?, file structure conflict

### ISSUE THREAD

**Issue by tjnz** [learn-co-curriculum/js-functions-lab#5]
This lab has 3 lights, in talking with an learn expert it is supposed to have 2.  Right now it requests local tests in addition to a fork and pull request.  Because it doesn't have any specs, you can't get all 3 greens and officially "pass" the lesson. 

Also, it asks you to code in js/function.js but there is not a js directory nor a solution.js file.  In the actual package it initially asks you to write in index.js which is different than the current README.

**Comment by pletcher** [comment]
Have you updated your `learn` gem? `gem update learn-co` should pull in the latest.

You'll want `learn-co` of at least version 3.4.5, and `learn-test` should be at least version 2.3.0. (You can get the version of `learn-test` by running `learn-test --version`.

If it's still an issue after upgrading, feel free to reopen.

**Comment by tjnz** [comment]
Yeah it still does not work.  I get this error (linux mint)

Checking for homebrew...
Updating brew...
Installing missing dependency node...
/home/tom/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:193:in `spawn': No such file or directory - brew (Errno::ENOENT)
    from /home/tom/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:193:in`popen_run'
    from /home/tom/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open3.rb:93:in `popen3'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/lib/learn_test/dependency.rb:36:in`run_install'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/lib/learn_test/dependencies/nodejs.rb:13:in `install'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/lib/learn_test/dependency.rb:10:in`execute'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/lib/learn_test/strategies/mocha.rb:28:in `check_dependencies'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/lib/learn_test/runner.rb:13:in`run'
    from /home/tom/.rvm/gems/ruby-2.2.2/gems/learn-test-2.3.1/bin/learn-test:56:in `<top (required)>'
    from /home/tom/.rvm/gems/ruby-2.2.2/bin/learn-test:23:in`load'
    from /home/tom/.rvm/gems/ruby-2.2.2/bin/learn-test:23:in `<main>'
    from /home/tom/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in`eval'
    from /home/tom/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by pletcher** [comment]
Oh yeah, that's definitely not going to work. Was that error output from `learn` or `learn-test`?

You'll need to have Node.js installed for `learn-test` to work. (`learn`, as far as I know, doesn't work on Linux.) It should be as simple as installing [n](https://github.com/tj/n) or [nvm](https://github.com/creationix/nvm) and installing v6.0.0 or greater of Node.js. Then run `learn-test` again.

**Comment by tjnz** [comment]
Yep! Thanks, was just going to write in.  I had to install brew and node.  Thanks again
