### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by glee38** [learn-co-curriculum/js-functions-lab#8]
<img width="1052" alt="screen shot 2016-07-21 at 8 35 06 pm" src="https://cloud.githubusercontent.com/assets/15304564/17043246/bf149e24-4f82-11e6-94fe-9e613c3082c8.png">

The above errors are displayed in my console when I run "npm run debug" in my terminal. I ran npm install before running "npm run debug", and had the debugger keyword in my second function as follows:

``` javascript
function sayHey() {
  return "Hey!";
}

function sayHeyFriend(name) {
  debugger;
}
```

When I hovered over "name" in Chrome, "Kristen" did not come up. Nor did it come up when I typed it into the console as outlined in the lab. 

<img width="1053" alt="screen shot 2016-07-21 at 8 39 58 pm" src="https://cloud.githubusercontent.com/assets/15304564/17043292/5c3d11e0-4f83-11e6-8895-41aead2d2b7e.png">

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
This lab doesn't yet have debugging support -- you meant https://github.com/glee38/javascript-intro-to-debugging-v-000, right?

**Comment by pletcher** [comment]
Hm -- those errors should be okay, actually. (I'm unable to reproduce exactly what you're seeing -- I _do_ see "Kristin" when hovering over the name, but it doesn't get added to `window` (which makes sense -- I must have missed the instructions to do that when editing this lab).

What version of Chrome are you running? I can't reproduce on v51.0.2704.103

**Comment by pletcher** [comment]
![screen shot 2016-07-22 at 11 59 43 am](https://cloud.githubusercontent.com/assets/2015049/17063133/cf19636e-5003-11e6-8268-2be27501b810.png)

For reference, this is what I see. You can see that `name` is in scope as `"Kristin"`.

**Comment by glee38** [comment]
I am using Chrome Version 51.0.2704.103 (64-bit) as well!

**Comment by glee38** [comment]
Hm.. that is so weird! I don't know why I am not seeing that in my debugger window!

**Comment by glee38** [comment]
Also, this is what I see in my Terminal when I run 'npm run debug'

<img width="622" alt="screen shot 2016-07-22 at 12 11 48 pm" src="https://cloud.githubusercontent.com/assets/15304564/17063496/95151382-5005-11e6-8332-07bbaa3c01b0.png">

**Comment by pletcher** [comment]
Yep, debugging _mocha is normal -- but it looks like another debugged
didn't quite shut down (this happens sometimes).

It's an easy fix, though. Just run `pgrep node`. You should see a number.
Then run `kill -9 NUMBER`, where NUMBER is the number from pgrep.

Try debugging again after that -- does it work?

**Comment by glee38** [comment]
Oh man, it is still not working :( I now seeing:

<img width="1047" alt="screen shot 2016-07-22 at 12 53 54 pm" src="https://cloud.githubusercontent.com/assets/15304564/17064630/7359a4be-500b-11e6-84ee-3f424947ebcf.png">

**Comment by pletcher** [comment]
`name` won't work in the console with this method, I'm afraid.

It's hard to debug this remotely, as it's clear that there's some kind of environment discrepancy between my machine and yours. Are you running the latest version of Node.js? Try `npm install -g n` and then `n latest` just in case.

I just pushed an update https://github.com/learn-co-students/javascript-intro-to-debugging-v-000 -- you should now be able to open `test/index-test.html` in the browser and debug that way (the instructions have been updated, too, under "The Easy Way").

Hopefully that works!

**Comment by glee38** [comment]
After uninstalling and reinstalling npm, it is now working! WOO! Thank you so much for your help :)

**Comment by glee38** [comment]
So sorry, one more thing - I just reforked this lab, and I don't see a test/index-test.html file! There is only an intro-test.js under the test folder

**Comment by pletcher** [comment]
Right -- this lab doesn't support debugging yet. You'll want this one: https://github.com/learn-co-students/javascript-intro-to-debugging-v-000 :)

**Comment by glee38** [comment]
ahh! I'm so sorry, I meant that I reforked the intro to debugging by writing "learn open" in my terminal, and I am seeing: 

<img width="802" alt="screen shot 2016-07-22 at 2 14 35 pm" src="https://cloud.githubusercontent.com/assets/15304564/17066803/b043a90a-5016-11e6-9ccf-d03195feb9fd.png">

But when I go to the github page, I see the links there! So I will manually fork it instead. Thank you again for all of your help :)
